"""empty message

Revision ID: 9bc3dd3aac12
Revises: 8346371c0cc3
Create Date: 2020-10-02 23:06:07.585020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bc3dd3aac12'
down_revision = '8346371c0cc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('tmdb_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('films', 'tmdb_id')
    # ### end Alembic commands ###
