"""empty message

Revision ID: f6d58c0bffa6
Revises: 9bc3dd3aac12
Create Date: 2020-10-09 01:07:44.414041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6d58c0bffa6'
down_revision = '9bc3dd3aac12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('film_meta', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('films', 'film_meta')
    # ### end Alembic commands ###
